### ISSUE TITLE
Docker image build error on DockerHub

### ISSUE THREAD

**Issue by rogargon** [silk-framework/silk#221]
The automated process to build the Silk Docker image on DockerHub is failing, for instance:
https://hub.docker.com/r/silkframework/silk-workbench/builds/bcmh6bau33gt7coeynxufjq/

Error:
```
java.lang.AssertionError: assertion failed: Required command line tools are missing
	at scala.Predef$.assert(Predef.scala:179)
	at ReactBuildHelper$.checkReactBuildTool(ReactBuildHelper.scala:38)
	at $c672a1c4ea6e9f13cdf1$$anonfun$reactComponents$1.apply$mcV$sp(build.sbt:204)
	at $c672a1c4ea6e9f13cdf1$$anonfun$reactComponents$1.apply(build.sbt:203)
	at $c672a1c4ea6e9f13cdf1$$anonfun$reactComponents$1.apply(build.sbt:203)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by andreas-schultz** [comment]
Thanks for the hint. This is fixed now.
