### ISSUE TITLE
`<Transforms>` needed?

### ISSUE THREAD

**Issue by Cerbal** [silk-framework/silk#40]
Hi Silk team, 

I am trying to run silk from xml configuration file. I have a configuration file that is nearly a copy of the one on: https://www.assembla.com/spaces/silk/wiki/Link_Specification_Language,

that I launch from my java code with : 
```java
File linkConfigFile = new File("data/toy_config.xml");
Silk.executeFile(linkConfigFile, null, Runtime.getRuntime().availableProcessors() - 1, false);
```
However, I receive the following error
```java
Exception in thread "main" de.fuberlin.wiwiss.silk.util.ValidationException: The content of element 'Silk' is not complete. One of '{Transforms}' is expected.
	at de.fuberlin.wiwiss.silk.util.ValidatingXMLReader$XmlReader.read(ValidatingXMLReader.scala:115)
	at de.fuberlin.wiwiss.silk.util.ValidatingXMLReader.apply(ValidatingXMLReader.scala:40)
	at de.fuberlin.wiwiss.silk.util.ValidatingXMLReader.apply(ValidatingXMLReader.scala:54)
	at de.fuberlin.wiwiss.silk.Silk$.executeFile(Silk.scala:93)
	at de.fuberlin.wiwiss.silk.Silk.executeFile(Silk.scala)
```

The error disappear when I add `<Transforms/>` after the `<Interlinks></Interlinks>` bloc, so I guess the syntax of the xml config file has evolved since the documentation on this page (https://www.assembla.com/spaces/silk/wiki/Link_Specification_Language). Where can I find an example of correct config file as for release 2.6.1?

**Comment by jgilme1** [comment]
I encountered the same problem. It seems that the documentation on Silk's website is not up to date with the XML descriptor file. You can check that file out here https://github.com/silk-framework/silk/blob/cbe7fac6852b6d93450a449ef338f5c78ff534d0/silk-core/src/main/resources/de/fuberlin/wiwiss/silk/LinkSpecificationLanguage.xsd. You can see that there is a required Transforms element. It seems that the development of the specification is in flux as now you need to specity a DatasetPlugin element in order to get output.

**Comment by robertisele** [comment]
The Transform Tag is no longer required. A working example is included in the current release: https://github.com/silk-framework/silk/releases
