### ISSUE TITLE
Bad dataset handling for CSV files

### ISSUE THREAD

**Issue by jplu** [silk-framework/silk#53]
Hello,

If you check this [screenshot](http://img4.hostingpics.net/pics/600007Capturedecran20160223a232313.png) you will be able to see that the blue dataset paths are in red on the schema, and the red dataset paths are in blue on the schema. As the colors are reversed Silk check the path in the wrong dataset (CSV file) and throws this exception:

```
[warn] o.s.r.a.G.Loading - Error loading resources
java.lang.Exception: Property /Financial+Institution+Name not found in CSV
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:139) ~[com.silk-framework.pluginscsv-2.7.0.jar:2.7.0]
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:135) ~[com.silk-framework.pluginscsv-2.7.0.jar:2.7.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[org.scala-lang.scala-library-2.11.7.jar:na]
[warn] o.s.r.a.G.Loading - Error loading resources
java.lang.Exception: Property /LegalAddress_Region_2 not found in CSV
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:139) ~[com.silk-framework.pluginscsv-2.7.0.jar:2.7.0]
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:135) ~[com.silk-framework.pluginscsv-2.7.0.jar:2.7.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[org.scala-lang.scala-library-2.11.7.jar:na]
[warn] o.s.r.a.G.Loading - Failed after 101ms: Property /LegalAddress_Region_2 not found in CSV
[ERROR] [02/23/2016 23:04:57.723] [play-akka.actor.default-dispatcher-33] [TaskInvocation] Property /LegalAddress_Region_2 not found in CSV
java.lang.Exception: Property /LegalAddress_Region_2 not found in CSV
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:139)
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:135)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.silkframework.plugins.dataset.csv.CsvSource.retrieveEntities(CsvSource.scala:135)
	at org.silkframework.plugins.dataset.csv.CsvSource.retrieve(CsvSource.scala:114)
	at org.silkframework.execution.Loader$LoadingThread.retrieveEntities(Loader.scala:79)
	at org.silkframework.execution.Loader$LoadingThread.run(Loader.scala:89)

[error] a.d.TaskInvocation - Property /LegalAddress_Region_2 not found in CSV
java.lang.Exception: Property /LegalAddress_Region_2 not found in CSV
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:139) ~[com.silk-framework.pluginscsv-2.7.0.jar:2.7.0]
	at org.silkframework.plugins.dataset.csv.CsvSource$$anonfun$6.apply(CsvSource.scala:135) ~[com.silk-framework.pluginscsv-2.7.0.jar:2.7.0]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[org.scala-lang.scala-library-2.11.7.jar:na]
```

P.S: as you can also see, there is some graphical bugs.

I'm using the 2.7.0 release.

Thanks in advance.

**Comment by robertisele** [comment]
It seems there is a bug in the rule editor in Silk 2.7.0, that does not serialize source and target paths properly. The bug should be fixed in the current master, I have uploaded a current build here:

https://drive.google.com/file/d/0BzPJGGjy3a9DYjZtendjTHUxY0U/view?usp=sharing

Could you please retest if your issue is fixed? You might need to re-add the source and target paths, I am sorry about that.

**Comment by jplu** [comment]
This seems to be fixed in this new version indeed.

Thanks!
