### ISSUE TITLE
Internal Server Error after build with JDK 16

### ISSUE THREAD

**Issue by Lars-H** [silk-framework/silk#540]
Hi,

I am trying to build the silk-workbench locally but I am running into some issues after there server is started.
I get the following prompt after running the `sbt "project workbench" run` command:

```
Mar 03, 2022 2:35:20 PM ReactBuildHelper$ yarnInstall
INFO: Setting up yarn workspaces environment...
Mar 03, 2022 2:35:33 PM ReactBuildHelper$ buildReactComponents
INFO: Building Workbench React UI for development, running task build-di-dev...
Mar 03, 2022 2:35:33 PM ReactBuildHelper$ yarnInstall
INFO: Setting up yarn workspaces environment...
Mar 03, 2022 2:36:30 PM ReactBuildHelper$ buildReactComponents
INFO: Finished building 'Workbench' React UI.

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /[0:0:0:0:0:0:0:0]:9000

(Server started, use Enter to stop and go back to the console...)
``` 

But when I am trying to access the server at `localhost:9000`, somehow the React UI is rebuilt as the console says:

```
  | => reactUI / buildDiReact 6s
```

And after a while, I get the following error 

```
2022-03-03 14:40:24,308 WARN  application Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2022-03-03 14:40:24,764 ERROR p.a.h.DefaultHttpErrorHandler

! @7mp8ggff3 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:254)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:302)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1297)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:775)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:790)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
	at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173)
	at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160)
	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$2(DevServerStart.scala:193)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:185)
	... 25 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
	at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
	at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 46 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
	at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	... 63 common frames omitted
Caused by: com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @33b27670
	at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:464)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
	at com.google.inject.internal.cglib.core.$KeyFactory$Generator.create(KeyFactory.java:221)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:174)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:157)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:149)
	at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:145)
	at com.google.inject.internal.cglib.core.$MethodWrapper.<clinit>(MethodWrapper.java:23)
	... 74 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @33b27670
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:61)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:52)
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
	... 71 common frames omitted
```

Has anyones seen the same issues and knows how this can be resolved?

Thanks and best regards

Lars

**Comment by andreas-schultz** [comment]
So far I have not seen this error. Which Java version are you using?
The build is regularly tested with JDK 8 and 11.

**Comment by Lars-H** [comment]
Hi Andreas,
thanks for the quick reply.
I am using the following Java Setup:
```
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

I will try it again with the suggestion versions.

**Comment by Lars-H** [comment]
Hi @andreas-schultz,

I have re-run the sbt build command with the JDK 8.
I don't get the server error anymore and the server seems to start properly.
However, when trying to access the Web UI on localhost, the ` reactUI / buildDiReact` is re-executed several times as shown in the following logs.
It says "Finished building 'Workbench' React UI." but then the process starts all over again.

Do you have any suggestion what the issue could be?

Thanks!
Lars

```
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

2022-03-07 15:42:33,696 WARN  application Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
2022-03-07 15:42:35,968 INFO  a.e.s.Slf4jLogger Slf4jLogger started
2022-03-07 15:42:36,109 INFO  play.api.Play Application started (Dev) (no global state)
2022-03-07 15:42:36,583 WARN  o.s.c.DefaultConfig Configuration file not found at: /Users/hla2rng/.silk/etc/dataintegration/conf/dataintegration.conf.
Falling back on default reference.conf file.
Possible fix: Map a volume with the config file to this location.
Otherwise set elds.home or $ELDS_HOME to point to the correct location.
2022-03-07 15:42:36,869 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:42:38,307 INFO  o.s.w.PluginBasedWorkspaceFactory Using configured workspace provider file
2022-03-07 15:42:38,324 INFO  o.s.w.PluginBasedWorkspaceFactory Using configured workspace repository type projectFile
2022-03-07 15:42:38,348 INFO  o.s.w.Workspace Loading registered prefixes...
2022-03-07 15:42:38,348 INFO  o.s.w.Workspace Starting workspace activities...
2022-03-07 15:42:38,378 INFO  o.s.r.a.Global uri pattern cache Waiting
2022-03-07 15:42:38,382 INFO  o.s.r.a.Global vocabulary cache Waiting
2022-03-07 15:42:38,383 INFO  o.s.w.Workspace Starting project activities...
2022-03-07 15:42:38,385 INFO  o.s.w.Workspace 0 projects loaded.
2022-03-07 15:42:38,386 INFO  o.s.r.a.Global vocabulary cache Running
2022-03-07 15:42:38,386 INFO  o.s.r.a.Global uri pattern cache Running
2022-03-07 15:42:38,391 INFO  o.s.w.a.t.GlobalUriPatternCache Global URI pattern cache is disabled, skipping URI pattern extraction in global URI pattern cache. Parameter: caches.global.uriPatternCache.enabled
2022-03-07 15:42:38,397 INFO  o.s.r.a.Global uri pattern cache Finished in 3ms
2022-03-07 15:42:38,401 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:42:38,401 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:42:38,405 INFO  o.s.r.a.Global vocabulary cache Finished in 16ms
2022-03-07 15:43:32,829 INFO  ReactBuildHelper$ Finished building 'Workbench' React UI.
2022-03-07 15:43:35,229 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:43:36,334 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:43:36,340 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:44:35,446 INFO  ReactBuildHelper$ Finished building 'Workbench' React UI.
2022-03-07 15:44:37,108 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:44:38,394 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:44:38,395 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:45:34,992 INFO  ReactBuildHelper$ Finished building 'Workbench' React UI.
2022-03-07 15:45:37,236 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:45:38,546 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:45:38,552 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:46:33,832 INFO  ReactBuildHelper$ Finished building 'Workbench' React UI.
2022-03-07 15:46:35,599 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:46:37,211 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:46:37,228 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:47:34,216 INFO  ReactBuildHelper$ Finished building 'Workbench' React UI.
2022-03-07 15:47:36,321 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:47:37,408 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:47:37,416 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:48:31,066 INFO  ReactBuildHelper$ Finished building 'Workbench' React UI.
2022-03-07 15:49:11,453 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...
2022-03-07 15:49:12,923 INFO  ReactBuildHelper$ Building Workbench React UI for development, running task build-di-dev...
2022-03-07 15:49:12,924 INFO  ReactBuildHelper$ Setting up yarn workspaces environment...


  | => reactUI / buildDiReact 9s
```

**Comment by andreas-schultz** [comment]
There has been a bug in the watch-mechanism. This is fixed now on the develop branch ([commit](https://github.com/silk-framework/silk/commit/c2043abf90af2e674ea2e3e16ddc954bb586fa21)).
