### ISSUE TITLE
Plugin loading "not a subtype" error

### ISSUE THREAD

**Issue by frmichel** [silk-framework/silk#99]
Hi all,

I'm trying to develop a simple plugin, however I'm stuck with a problem at start time. Seems that the Java Service Provider can't load the plugin:

Exception in thread "main" java.util.ServiceConfigurationError: org.silkframework.runtime.plugin.PluginModule: Provider <_my plugin_> not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.silkframework.runtime.plugin.PluginRegistry$.registerJars(PluginRegistry.scala:140)
	at org.silkframework.runtime.plugin.PluginRegistry$.<init>(PluginRegistry.scala:28)
        ...

I have tried either putting the plugin in the ~/.silk/plugins folder, or putting it on the classpath. 
In both cases, the issue occurs.

I've googled the problem, and it seems that many people do have that issue when playing with plugins. That would be related with real time issues in the class loader, but nobody actually gives an solution and this is generally solved mysteriously by upgrading libs. 
Here, I just have the silk jar, my jar with a single plugin class, that could not be more simple.

I have tried this with Silk 2.7.0 and 2.7.1, same behaviour.

Have you ever experienced this?

Thx for your help.
  Franck.

**Comment by frmichel** [comment]
Hi all,

Actually I finally ended up finding the problem, which is my mistake: the file META-INF/services/org.silkframework.runtime.plugin.PluginModule must list the PluginModules class(es), that itself lists the plugins.

Typically, in the case below, the file must contain MyPlugins, not MyTransformer.

`class MyPlugins extends PluginModule {
  override def pluginClasses = Seq(classOf[MyPlugin])
}

case class MyTransformer() extends SimpleTransformer {
  override def evaluate(value: String) = ...   } 
}`

Sorry about that :)
